name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: deploy-telehed

    strategy:
      matrix:
        node-version: [14.20.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: rebuild dash
      run: yarn build
    - name: remove old files dash
      run: sudo rm -r /var/www/html/apollo
    - name: copy dash to correct folder
      run: sudo cp -r ~/actions-runner/_work/higia-apollo/higia-apollo/dist/ /var/www/html/apollo
    - name: allowed correct acess to files
      run: sudo chown -R www-data:www-data /var/www/html/dash
    - name: restart nginx
      run: sudo systemctl restart nginx
